language: java
# sudo, dist, and group are required for oraclejdk9.
# Remove them as soon as container infra has java9 support.
sudo: required
dist: trusty
group: edge
# Environment variables are for Java9.
# But they need to work on Java 8, too.
# Hence the IgnoreUnrecognizedVMOptions
env:
  global:
    - JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED'
    - GRADLE_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED'
jdk:
  - oraclejdk8
  - oraclejdk9
# A peculiarity of dependency caching in Gradle means that to avoid uploading the cache after every build the following
# lines must be added:
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
